### ISSUE TITLE
Label event arguments are double quoted

### ISSUE THREAD

**Issue by goldcougar** [Servoy/bootstrapcomponents#10]
In 1.5.2 things work correctly, but 1.6.0 and after all have this bug.

When passing arguments on label elements through the UI designer, the events receive the argument with an extra quote around it.  For example, if you set the argument to 'test', and output the argument in the method, it will show "'test'" with double quotes around the single quotes and value.  Doesn't seem to happen on buttons.

Here is an example with a label:
![image](https://user-images.githubusercontent.com/10157914/80146429-d5a62e00-857f-11ea-8f82-502e2f2b9d40.png)

![image](https://user-images.githubusercontent.com/10157914/80146579-0d14da80-8580-11ea-90af-bf575d324613.png)

**Comment by goldcougar** [comment]
@paronne  My hunch is this commit might be the conflict?  https://github.com/Servoy/bootstrapcomponents/commit/a8146109f2ce1991e42d744af5a833ddfb46668b

It seems to be the only difference in the label component between version 1.5.2 and 1.6.0 where it broke.

**Comment by seanthomasdevlin** [comment]
Linked to internal case:
https://support.servoy.com/browse/SVY-14944

**Comment by goldcougar** [comment]
Updated internal case: https://support.servoy.com/browse/SVY-14934
