### ISSUE TITLE
How to use Data List 

### ISSUE THREAD

**Issue by juanetec** [Servoy/bootstrapcomponents#11]
Hi,
have to be really simple but I don't know how to use.
It is like the ListBox from smart client?
I Could no found any info about this.

Un Saludo

Juan Ramírez

**Comment by seanthomasdevlin** [comment]
Hola Juan,

This component is a mobile/touch-friendly component. It is poorly documented and we are refactoring this a bit, so it is not confused to be used for desktop-browser apps.

ServoyDefault > ListBox is still supported, but the whole package (minus a few new ones) will be shortly deprecated as those components are for legacy-compatibility only. It will continue to function, but hidden from form palette.

I could recommend the ServoyExtra > Select2Tokenizer for non-mobile

**Comment by juanetec** [comment]
Hi Sean,
thanks for your response.
Un Saludo
