### ISSUE TITLE
Question on version compatibility

### ISSUE THREAD

**Issue by mboegem** [Servoy/bootstrapcomponents#12]
why are the latest versions (3.0 and up) only available for 2020.6?
We're still on 2020.3 and not planning an update soon, however the latest version contains a couple of nice improvements that we'd like to use.

**Comment by jcompagner** [comment]
because there are a lot of things new that only 2020.6 supports
They could be working on .3 but they could also fail in some area's you can always try to use the release zip directly from github

**Comment by seanthomasdevlin** [comment]
Hi Marc,

The latest 3+ versions depend on core changes in the Servoy IDE, including "hiding" the package in the palette, instead showing components by more useful categories. Moreover, we deprecated Servoy Default components, moving some components to bootstrap, so there would then be collisions. You can try it, not sure what will happen
