### ISSUE TITLE
Combo box doesnt fill values and results in error in console.

### ISSUE THREAD

**Issue by MikePogson** [Servoy/bootstrapcomponents#13]
I am running into an issue with the combo box that I am not sure how to fix or where the problem is.  I have attached a couple combo box's to a form and load them with a value list when I show the form.  Everything works fine when I run with developer but as soon as I deploy the solution to a server the dropdowns dont fill in with data and I end up with an error in the console.  Is there something I am missing?

Error: [$injector:unpr] http://errors.angularjs.org/1.7.7/$injector/unpr?p0=bcShowDisplayValueFilterProvider%20%3C-%20bcShowDisplayValueFilter
    at servoy_thirdparty_svygrp1754343cd69.js:10
    at servoy_thirdparty_svygrp1754343cd69.js:49
    at Object.d [as get] (servoy_thirdparty_svygrp1754343cd69.js:46)
    at servoy_thirdparty_svygrp1754343cd69.js:49
    at Object.d [as get] (servoy_thirdparty_svygrp1754343cd69.js:46)
    at servoy_thirdparty_svygrp1754343cd69.js:175
    at Z (servoy_thirdparty_svygrp1754343cd69.js:133)
    at servoy_thirdparty_svygrp1754343cd69.js:133
    at r (servoy_thirdparty_svygrp1754343cd69.js:11)
    at Z (servoy_thirdparty_svygrp1754343cd69.js:133)
(anonymous) @ servoy_thirdparty_svygrp1754343cd69.js:130
(anonymous) @ servoy_thirdparty_svygrp1754343cd69.js:102
$digest @ servoy_thirdparty_svygrp1754343cd69.js:155
$apply @ servoy_thirdparty_svygrp1754343cd69.js:158
(anonymous) @ servoy_thirdparty_svygrp1754343cd69.js:201
dispatch @ servoy_thirdparty_svygrp1754343cd69.js:2
y.handle @ servoy_thirdparty_svygrp1754343cd69.js:2

**Comment by jcompagner** [comment]
how did you create the WAR? Did you disabled or enabled any components/packages?
because where it complains about is a filter that is in /lib/js/bscomponents-common.js file of the bootstrap package.
it should just also include that into your war but somehow it didn't seem to do that.

If you have the war for us then we can have a look or only part of the war (only the "wro" dir and all the properties files that are in WEB-INF dir)

**Comment by MikePogson** [comment]
I dont include or exclude any packages directly I assumed that would include all packages in the solution.  All other componenets seems to be working correctly.  LIke the navbar and buttons we use.  Here is a zip with what you requested.  I also can see that js file in the location you are talking about so I would assume it got included.
[export.zip](https://github.com/Servoy/bootstrapcomponents/files/5416982/export.zip)

**Comment by lvostinar** [comment]
Fixed by: https://support.servoy.com/browse/SVY-15601
